// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EliminarproductosdelcarritoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void eliminarproductosdelcarrito() {
    driver.get("http://localhost:8000/?post_type=product");
    driver.manage().window().setSize(new Dimension(974, 1039));
    driver.findElement(By.cssSelector(".wc-block-product:nth-child(1) .wp-block-button__link > span")).click();
    driver.findElement(By.cssSelector(".wc-block-product:nth-child(1) .wp-block-button__link > span")).click();
    driver.findElement(By.cssSelector(".wc-block-product:nth-child(2) .wp-block-button__link > span")).click();
    driver.findElement(By.cssSelector("path:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".wc-block-cart-items__row:nth-child(2) .wc-block-cart-item__remove-link")).click();
    assertThat(driver.findElement(By.cssSelector(".wc-block-components-totals-item__value")).getText(), is("$4,099.00"));
  }
}
