// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrodeusuariosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrodeusuarios() {
    driver.get("http://localhost:8000/?post_type=product/wp-login.php?redirect_to=http%3A%2F%2Flocalhost%3A8000%2Fwp-admin%2Fusers.php&reauth=1");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.id("user_login")).sendKeys("JuanDa");
    driver.findElement(By.id("user_pass")).click();
    driver.findElement(By.id("user_pass")).click();
    driver.findElement(By.id("user_pass")).sendKeys("QusJHuhFM!5l0nyAvd");
    driver.findElement(By.id("wp-submit")).click();
    driver.findElement(By.cssSelector(".page-title-action")).click();
    driver.findElement(By.id("user_login")).click();
    driver.findElement(By.id("user_login")).sendKeys("Simon");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("SimonG@gmail.com");
    driver.findElement(By.id("first_name")).click();
    driver.findElement(By.id("first_name")).sendKeys("Simon");
    driver.findElement(By.id("last_name")).click();
    driver.findElement(By.id("last_name")).sendKeys("Gallego");
    driver.findElement(By.id("createusersub")).click();
    assertThat(driver.findElement(By.xpath("//p[contains(.,\'Nuevo usuario creado. Editar usuario\')]")).getText(), is("Nuevo usuario creado. Editar usuario"));
  }
}
